/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthPendingAccessImport } from './routes/auth/pending-access'
import { Route as AuthOnboardingImport } from './routes/auth/onboarding'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AuthCreateAccountImport } from './routes/auth/create-account'
import { Route as AuthAcceptInviteImport } from './routes/auth/accept-invite'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminCompaniesImport } from './routes/admin/companies'
import { Route as AdminAccessRequestsImport } from './routes/admin/access-requests'
import { Route as DashboardProjectsIndexImport } from './routes/dashboard/projects/index'
import { Route as DashboardFieldIndexImport } from './routes/dashboard/field/index'
import { Route as DashboardCompanyIndexImport } from './routes/dashboard/company/index'
import { Route as DashboardAnalyticsIndexImport } from './routes/dashboard/analytics/index'
import { Route as DashboardProjectsProjectIdImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardCompanyRolesImport } from './routes/dashboard/company/roles'
import { Route as DashboardCompanyProjectsImport } from './routes/dashboard/company/projects'
import { Route as DashboardCompanyMembersImport } from './routes/dashboard/company/members'
import { Route as DashboardCompanyInvitationsImport } from './routes/dashboard/company/invitations'
import { Route as DashboardProjectsProjectIdIndexImport } from './routes/dashboard/projects/$projectId.index'
import { Route as DashboardAnalyticsProjectsIndexImport } from './routes/dashboard/analytics/projects.index'
import { Route as DashboardProjectsProjectIdEditImport } from './routes/dashboard/projects/$projectId.edit'
import { Route as DashboardProjectsProjectIdBuildingsImport } from './routes/dashboard/projects/$projectId.buildings'
import { Route as DashboardFieldProjectsProjectIdImport } from './routes/dashboard/field/projects.$projectId'
import { Route as DashboardAnalyticsProjectsProjectIdImport } from './routes/dashboard/analytics/projects.$projectId'
import { Route as DashboardProjectsProjectIdBuildingsIndexImport } from './routes/dashboard/projects/$projectId.buildings.index'
import { Route as DashboardProjectsProjectIdPoursNewImport } from './routes/dashboard/projects/$projectId.pours.new'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdIndexImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId.index'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdFloorsImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId.floors'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdEditImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId.edit'
import { Route as DashboardFieldProjectsProjectIdPoursQuickAddImport } from './routes/dashboard/field/projects.$projectId.pours.quick-add'
import { Route as DashboardFieldProjectsProjectIdPhotosUploadImport } from './routes/dashboard/field/projects.$projectId.photos.upload'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId.floors.$floorId'
import { Route as DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditImport } from './routes/dashboard/projects/$projectId.buildings.$buildingId.floors.$floorId.edit'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthPendingAccessRoute = AuthPendingAccessImport.update({
  id: '/auth/pending-access',
  path: '/auth/pending-access',
  getParentRoute: () => rootRoute,
} as any)

const AuthOnboardingRoute = AuthOnboardingImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthCreateAccountRoute = AuthCreateAccountImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRoute,
} as any)

const AuthAcceptInviteRoute = AuthAcceptInviteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCompaniesRoute = AdminCompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAccessRequestsRoute = AdminAccessRequestsImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardProjectsIndexRoute = DashboardProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFieldIndexRoute = DashboardFieldIndexImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyIndexRoute = DashboardCompanyIndexImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProjectsProjectIdRoute = DashboardProjectsProjectIdImport.update(
  {
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

const DashboardCompanyRolesRoute = DashboardCompanyRolesImport.update({
  id: '/company/roles',
  path: '/company/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyProjectsRoute = DashboardCompanyProjectsImport.update({
  id: '/company/projects',
  path: '/company/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyMembersRoute = DashboardCompanyMembersImport.update({
  id: '/company/members',
  path: '/company/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyInvitationsRoute =
  DashboardCompanyInvitationsImport.update({
    id: '/company/invitations',
    path: '/company/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

const DashboardAnalyticsProjectsIndexRoute =
  DashboardAnalyticsProjectsIndexImport.update({
    id: '/analytics/projects/',
    path: '/analytics/projects/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdEditRoute =
  DashboardProjectsProjectIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsRoute =
  DashboardProjectsProjectIdBuildingsImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

const DashboardFieldProjectsProjectIdRoute =
  DashboardFieldProjectsProjectIdImport.update({
    id: '/field/projects/$projectId',
    path: '/field/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAnalyticsProjectsProjectIdRoute =
  DashboardAnalyticsProjectsProjectIdImport.update({
    id: '/analytics/projects/$projectId',
    path: '/analytics/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsIndexRoute =
  DashboardProjectsProjectIdBuildingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdBuildingsRoute,
  } as any)

const DashboardProjectsProjectIdPoursNewRoute =
  DashboardProjectsProjectIdPoursNewImport.update({
    id: '/pours/new',
    path: '/pours/new',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdImport.update({
    id: '/$buildingId',
    path: '/$buildingId',
    getParentRoute: () => DashboardProjectsProjectIdBuildingsRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdBuildingsBuildingIdRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsImport.update({
    id: '/floors',
    path: '/floors',
    getParentRoute: () => DashboardProjectsProjectIdBuildingsBuildingIdRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdEditRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectsProjectIdBuildingsBuildingIdRoute,
  } as any)

const DashboardFieldProjectsProjectIdPoursQuickAddRoute =
  DashboardFieldProjectsProjectIdPoursQuickAddImport.update({
    id: '/pours/quick-add',
    path: '/pours/quick-add',
    getParentRoute: () => DashboardFieldProjectsProjectIdRoute,
  } as any)

const DashboardFieldProjectsProjectIdPhotosUploadRoute =
  DashboardFieldProjectsProjectIdPhotosUploadImport.update({
    id: '/photos/upload',
    path: '/photos/upload',
    getParentRoute: () => DashboardFieldProjectsProjectIdRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdImport.update({
    id: '/$floorId',
    path: '/$floorId',
    getParentRoute: () =>
      DashboardProjectsProjectIdBuildingsBuildingIdFloorsRoute,
  } as any)

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute =
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/access-requests': {
      id: '/admin/access-requests'
      path: '/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteImport
      parentRoute: typeof rootRoute
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/auth/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingImport
      parentRoute: typeof rootRoute
    }
    '/auth/pending-access': {
      id: '/auth/pending-access'
      path: '/auth/pending-access'
      fullPath: '/auth/pending-access'
      preLoaderRoute: typeof AuthPendingAccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/invitations': {
      id: '/dashboard/company/invitations'
      path: '/company/invitations'
      fullPath: '/dashboard/company/invitations'
      preLoaderRoute: typeof DashboardCompanyInvitationsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/members': {
      id: '/dashboard/company/members'
      path: '/company/members'
      fullPath: '/dashboard/company/members'
      preLoaderRoute: typeof DashboardCompanyMembersImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/projects': {
      id: '/dashboard/company/projects'
      path: '/company/projects'
      fullPath: '/dashboard/company/projects'
      preLoaderRoute: typeof DashboardCompanyProjectsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/roles': {
      id: '/dashboard/company/roles'
      path: '/company/roles'
      fullPath: '/dashboard/company/roles'
      preLoaderRoute: typeof DashboardCompanyRolesImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/': {
      id: '/dashboard/company/'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof DashboardCompanyIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/field/': {
      id: '/dashboard/field/'
      path: '/field'
      fullPath: '/dashboard/field'
      preLoaderRoute: typeof DashboardFieldIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/analytics/projects/$projectId': {
      id: '/dashboard/analytics/projects/$projectId'
      path: '/analytics/projects/$projectId'
      fullPath: '/dashboard/analytics/projects/$projectId'
      preLoaderRoute: typeof DashboardAnalyticsProjectsProjectIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/field/projects/$projectId': {
      id: '/dashboard/field/projects/$projectId'
      path: '/field/projects/$projectId'
      fullPath: '/dashboard/field/projects/$projectId'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectId/buildings': {
      id: '/dashboard/projects/$projectId/buildings'
      path: '/buildings'
      fullPath: '/dashboard/projects/$projectId/buildings'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
    '/dashboard/projects/$projectId/edit': {
      id: '/dashboard/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectId/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
    '/dashboard/analytics/projects/': {
      id: '/dashboard/analytics/projects/'
      path: '/analytics/projects'
      fullPath: '/dashboard/analytics/projects'
      preLoaderRoute: typeof DashboardAnalyticsProjectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId'
      path: '/$buildingId'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsImport
    }
    '/dashboard/projects/$projectId/pours/new': {
      id: '/dashboard/projects/$projectId/pours/new'
      path: '/pours/new'
      fullPath: '/dashboard/projects/$projectId/pours/new'
      preLoaderRoute: typeof DashboardProjectsProjectIdPoursNewImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
    '/dashboard/projects/$projectId/buildings/': {
      id: '/dashboard/projects/$projectId/buildings/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/buildings/'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsIndexImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsImport
    }
    '/dashboard/field/projects/$projectId/photos/upload': {
      id: '/dashboard/field/projects/$projectId/photos/upload'
      path: '/photos/upload'
      fullPath: '/dashboard/field/projects/$projectId/photos/upload'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdPhotosUploadImport
      parentRoute: typeof DashboardFieldProjectsProjectIdImport
    }
    '/dashboard/field/projects/$projectId/pours/quick-add': {
      id: '/dashboard/field/projects/$projectId/pours/quick-add'
      path: '/pours/quick-add'
      fullPath: '/dashboard/field/projects/$projectId/pours/quick-add'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdPoursQuickAddImport
      parentRoute: typeof DashboardFieldProjectsProjectIdImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId/edit': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdEditImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId/floors': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId/floors'
      path: '/floors'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId/floors'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId/': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdIndexImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId'
      path: '/$floorId'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsImport
    }
    '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit': {
      id: '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditImport
      parentRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteChildren {
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute
}

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteChildren: DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteChildren =
  {
    DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute,
  }

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren =
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRoute._addFileChildren(
    DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteChildren,
  )

interface DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteChildren {
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren
}

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteChildren: DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteChildren =
  {
    DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren,
  }

const DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren =
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsRoute._addFileChildren(
    DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteChildren,
  )

interface DashboardProjectsProjectIdBuildingsBuildingIdRouteChildren {
  DashboardProjectsProjectIdBuildingsBuildingIdEditRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdEditRoute
  DashboardProjectsProjectIdBuildingsBuildingIdFloorsRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren
  DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute
}

const DashboardProjectsProjectIdBuildingsBuildingIdRouteChildren: DashboardProjectsProjectIdBuildingsBuildingIdRouteChildren =
  {
    DashboardProjectsProjectIdBuildingsBuildingIdEditRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdEditRoute,
    DashboardProjectsProjectIdBuildingsBuildingIdFloorsRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren,
    DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute,
  }

const DashboardProjectsProjectIdBuildingsBuildingIdRouteWithChildren =
  DashboardProjectsProjectIdBuildingsBuildingIdRoute._addFileChildren(
    DashboardProjectsProjectIdBuildingsBuildingIdRouteChildren,
  )

interface DashboardProjectsProjectIdBuildingsRouteChildren {
  DashboardProjectsProjectIdBuildingsBuildingIdRoute: typeof DashboardProjectsProjectIdBuildingsBuildingIdRouteWithChildren
  DashboardProjectsProjectIdBuildingsIndexRoute: typeof DashboardProjectsProjectIdBuildingsIndexRoute
}

const DashboardProjectsProjectIdBuildingsRouteChildren: DashboardProjectsProjectIdBuildingsRouteChildren =
  {
    DashboardProjectsProjectIdBuildingsBuildingIdRoute:
      DashboardProjectsProjectIdBuildingsBuildingIdRouteWithChildren,
    DashboardProjectsProjectIdBuildingsIndexRoute:
      DashboardProjectsProjectIdBuildingsIndexRoute,
  }

const DashboardProjectsProjectIdBuildingsRouteWithChildren =
  DashboardProjectsProjectIdBuildingsRoute._addFileChildren(
    DashboardProjectsProjectIdBuildingsRouteChildren,
  )

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdBuildingsRoute: typeof DashboardProjectsProjectIdBuildingsRouteWithChildren
  DashboardProjectsProjectIdEditRoute: typeof DashboardProjectsProjectIdEditRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
  DashboardProjectsProjectIdPoursNewRoute: typeof DashboardProjectsProjectIdPoursNewRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdBuildingsRoute:
      DashboardProjectsProjectIdBuildingsRouteWithChildren,
    DashboardProjectsProjectIdEditRoute: DashboardProjectsProjectIdEditRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
    DashboardProjectsProjectIdPoursNewRoute:
      DashboardProjectsProjectIdPoursNewRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardFieldProjectsProjectIdRouteChildren {
  DashboardFieldProjectsProjectIdPhotosUploadRoute: typeof DashboardFieldProjectsProjectIdPhotosUploadRoute
  DashboardFieldProjectsProjectIdPoursQuickAddRoute: typeof DashboardFieldProjectsProjectIdPoursQuickAddRoute
}

const DashboardFieldProjectsProjectIdRouteChildren: DashboardFieldProjectsProjectIdRouteChildren =
  {
    DashboardFieldProjectsProjectIdPhotosUploadRoute:
      DashboardFieldProjectsProjectIdPhotosUploadRoute,
    DashboardFieldProjectsProjectIdPoursQuickAddRoute:
      DashboardFieldProjectsProjectIdPoursQuickAddRoute,
  }

const DashboardFieldProjectsProjectIdRouteWithChildren =
  DashboardFieldProjectsProjectIdRoute._addFileChildren(
    DashboardFieldProjectsProjectIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCompanyInvitationsRoute: typeof DashboardCompanyInvitationsRoute
  DashboardCompanyMembersRoute: typeof DashboardCompanyMembersRoute
  DashboardCompanyProjectsRoute: typeof DashboardCompanyProjectsRoute
  DashboardCompanyRolesRoute: typeof DashboardCompanyRolesRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCompanyIndexRoute: typeof DashboardCompanyIndexRoute
  DashboardFieldIndexRoute: typeof DashboardFieldIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardAnalyticsProjectsProjectIdRoute: typeof DashboardAnalyticsProjectsProjectIdRoute
  DashboardFieldProjectsProjectIdRoute: typeof DashboardFieldProjectsProjectIdRouteWithChildren
  DashboardAnalyticsProjectsIndexRoute: typeof DashboardAnalyticsProjectsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCompanyInvitationsRoute: DashboardCompanyInvitationsRoute,
  DashboardCompanyMembersRoute: DashboardCompanyMembersRoute,
  DashboardCompanyProjectsRoute: DashboardCompanyProjectsRoute,
  DashboardCompanyRolesRoute: DashboardCompanyRolesRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCompanyIndexRoute: DashboardCompanyIndexRoute,
  DashboardFieldIndexRoute: DashboardFieldIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardAnalyticsProjectsProjectIdRoute:
    DashboardAnalyticsProjectsProjectIdRoute,
  DashboardFieldProjectsProjectIdRoute:
    DashboardFieldProjectsProjectIdRouteWithChildren,
  DashboardAnalyticsProjectsIndexRoute: DashboardAnalyticsProjectsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company': typeof DashboardCompanyIndexRoute
  '/dashboard/field': typeof DashboardFieldIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectId': typeof DashboardAnalyticsProjectsProjectIdRoute
  '/dashboard/field/projects/$projectId': typeof DashboardFieldProjectsProjectIdRouteWithChildren
  '/dashboard/projects/$projectId/buildings': typeof DashboardProjectsProjectIdBuildingsRouteWithChildren
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/analytics/projects': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/buildings/$buildingId': typeof DashboardProjectsProjectIdBuildingsBuildingIdRouteWithChildren
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
  '/dashboard/projects/$projectId/buildings/': typeof DashboardProjectsProjectIdBuildingsIndexRoute
  '/dashboard/field/projects/$projectId/photos/upload': typeof DashboardFieldProjectsProjectIdPhotosUploadRoute
  '/dashboard/field/projects/$projectId/pours/quick-add': typeof DashboardFieldProjectsProjectIdPoursQuickAddRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdEditRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId/': typeof DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company': typeof DashboardCompanyIndexRoute
  '/dashboard/field': typeof DashboardFieldIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectId': typeof DashboardAnalyticsProjectsProjectIdRoute
  '/dashboard/field/projects/$projectId': typeof DashboardFieldProjectsProjectIdRouteWithChildren
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/analytics/projects': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
  '/dashboard/projects/$projectId/buildings': typeof DashboardProjectsProjectIdBuildingsIndexRoute
  '/dashboard/field/projects/$projectId/photos/upload': typeof DashboardFieldProjectsProjectIdPhotosUploadRoute
  '/dashboard/field/projects/$projectId/pours/quick-add': typeof DashboardFieldProjectsProjectIdPoursQuickAddRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdEditRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId': typeof DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company/': typeof DashboardCompanyIndexRoute
  '/dashboard/field/': typeof DashboardFieldIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectId': typeof DashboardAnalyticsProjectsProjectIdRoute
  '/dashboard/field/projects/$projectId': typeof DashboardFieldProjectsProjectIdRouteWithChildren
  '/dashboard/projects/$projectId/buildings': typeof DashboardProjectsProjectIdBuildingsRouteWithChildren
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/analytics/projects/': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/dashboard/projects/$projectId/buildings/$buildingId': typeof DashboardProjectsProjectIdBuildingsBuildingIdRouteWithChildren
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
  '/dashboard/projects/$projectId/buildings/': typeof DashboardProjectsProjectIdBuildingsIndexRoute
  '/dashboard/field/projects/$projectId/photos/upload': typeof DashboardFieldProjectsProjectIdPhotosUploadRoute
  '/dashboard/field/projects/$projectId/pours/quick-add': typeof DashboardFieldProjectsProjectIdPoursQuickAddRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdEditRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId/': typeof DashboardProjectsProjectIdBuildingsBuildingIdIndexRoute
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdRouteWithChildren
  '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit': typeof DashboardProjectsProjectIdBuildingsBuildingIdFloorsFloorIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/projects/$projectId'
    | '/dashboard/analytics'
    | '/dashboard/company'
    | '/dashboard/field'
    | '/dashboard/projects'
    | '/dashboard/analytics/projects/$projectId'
    | '/dashboard/field/projects/$projectId'
    | '/dashboard/projects/$projectId/buildings'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/analytics/projects'
    | '/dashboard/projects/$projectId/'
    | '/dashboard/projects/$projectId/buildings/$buildingId'
    | '/dashboard/projects/$projectId/pours/new'
    | '/dashboard/projects/$projectId/buildings/'
    | '/dashboard/field/projects/$projectId/photos/upload'
    | '/dashboard/field/projects/$projectId/pours/quick-add'
    | '/dashboard/projects/$projectId/buildings/$buildingId/edit'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors'
    | '/dashboard/projects/$projectId/buildings/$buildingId/'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/analytics'
    | '/dashboard/company'
    | '/dashboard/field'
    | '/dashboard/projects'
    | '/dashboard/analytics/projects/$projectId'
    | '/dashboard/field/projects/$projectId'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/analytics/projects'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/$projectId/pours/new'
    | '/dashboard/projects/$projectId/buildings'
    | '/dashboard/field/projects/$projectId/photos/upload'
    | '/dashboard/field/projects/$projectId/pours/quick-add'
    | '/dashboard/projects/$projectId/buildings/$buildingId/edit'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors'
    | '/dashboard/projects/$projectId/buildings/$buildingId'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/projects/$projectId'
    | '/dashboard/analytics/'
    | '/dashboard/company/'
    | '/dashboard/field/'
    | '/dashboard/projects/'
    | '/dashboard/analytics/projects/$projectId'
    | '/dashboard/field/projects/$projectId'
    | '/dashboard/projects/$projectId/buildings'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/analytics/projects/'
    | '/dashboard/projects/$projectId/'
    | '/dashboard/projects/$projectId/buildings/$buildingId'
    | '/dashboard/projects/$projectId/pours/new'
    | '/dashboard/projects/$projectId/buildings/'
    | '/dashboard/field/projects/$projectId/photos/upload'
    | '/dashboard/field/projects/$projectId/pours/quick-add'
    | '/dashboard/projects/$projectId/buildings/$buildingId/edit'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors'
    | '/dashboard/projects/$projectId/buildings/$buildingId/'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId'
    | '/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthPendingAccessRoute: typeof AuthPendingAccessRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthPendingAccessRoute: AuthPendingAccessRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/dashboard",
        "/auth/accept-invite",
        "/auth/create-account",
        "/auth/forgot-password",
        "/auth/onboarding",
        "/auth/pending-access",
        "/auth/reset-password",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/access-requests",
        "/admin/companies",
        "/admin/users",
        "/admin/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/company/invitations",
        "/dashboard/company/members",
        "/dashboard/company/projects",
        "/dashboard/company/roles",
        "/dashboard/projects/$projectId",
        "/dashboard/analytics/",
        "/dashboard/company/",
        "/dashboard/field/",
        "/dashboard/projects/",
        "/dashboard/analytics/projects/$projectId",
        "/dashboard/field/projects/$projectId",
        "/dashboard/analytics/projects/"
      ]
    },
    "/admin/access-requests": {
      "filePath": "admin/access-requests.tsx",
      "parent": "/admin"
    },
    "/admin/companies": {
      "filePath": "admin/companies.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/auth/accept-invite": {
      "filePath": "auth/accept-invite.tsx"
    },
    "/auth/create-account": {
      "filePath": "auth/create-account.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/onboarding": {
      "filePath": "auth/onboarding.tsx"
    },
    "/auth/pending-access": {
      "filePath": "auth/pending-access.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/invitations": {
      "filePath": "dashboard/company/invitations.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/members": {
      "filePath": "dashboard/company/members.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/projects": {
      "filePath": "dashboard/company/projects.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/roles": {
      "filePath": "dashboard/company/roles.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectId": {
      "filePath": "dashboard/projects/$projectId.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/projects/$projectId/buildings",
        "/dashboard/projects/$projectId/edit",
        "/dashboard/projects/$projectId/",
        "/dashboard/projects/$projectId/pours/new"
      ]
    },
    "/dashboard/analytics/": {
      "filePath": "dashboard/analytics/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/": {
      "filePath": "dashboard/company/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/field/": {
      "filePath": "dashboard/field/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/": {
      "filePath": "dashboard/projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/analytics/projects/$projectId": {
      "filePath": "dashboard/analytics/projects.$projectId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/field/projects/$projectId": {
      "filePath": "dashboard/field/projects.$projectId.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/field/projects/$projectId/photos/upload",
        "/dashboard/field/projects/$projectId/pours/quick-add"
      ]
    },
    "/dashboard/projects/$projectId/buildings": {
      "filePath": "dashboard/projects/$projectId.buildings.tsx",
      "parent": "/dashboard/projects/$projectId",
      "children": [
        "/dashboard/projects/$projectId/buildings/$buildingId",
        "/dashboard/projects/$projectId/buildings/"
      ]
    },
    "/dashboard/projects/$projectId/edit": {
      "filePath": "dashboard/projects/$projectId.edit.tsx",
      "parent": "/dashboard/projects/$projectId"
    },
    "/dashboard/analytics/projects/": {
      "filePath": "dashboard/analytics/projects.index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectId/": {
      "filePath": "dashboard/projects/$projectId.index.tsx",
      "parent": "/dashboard/projects/$projectId"
    },
    "/dashboard/projects/$projectId/buildings/$buildingId": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.tsx",
      "parent": "/dashboard/projects/$projectId/buildings",
      "children": [
        "/dashboard/projects/$projectId/buildings/$buildingId/edit",
        "/dashboard/projects/$projectId/buildings/$buildingId/floors",
        "/dashboard/projects/$projectId/buildings/$buildingId/"
      ]
    },
    "/dashboard/projects/$projectId/pours/new": {
      "filePath": "dashboard/projects/$projectId.pours.new.tsx",
      "parent": "/dashboard/projects/$projectId"
    },
    "/dashboard/projects/$projectId/buildings/": {
      "filePath": "dashboard/projects/$projectId.buildings.index.tsx",
      "parent": "/dashboard/projects/$projectId/buildings"
    },
    "/dashboard/field/projects/$projectId/photos/upload": {
      "filePath": "dashboard/field/projects.$projectId.photos.upload.tsx",
      "parent": "/dashboard/field/projects/$projectId"
    },
    "/dashboard/field/projects/$projectId/pours/quick-add": {
      "filePath": "dashboard/field/projects.$projectId.pours.quick-add.tsx",
      "parent": "/dashboard/field/projects/$projectId"
    },
    "/dashboard/projects/$projectId/buildings/$buildingId/edit": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.edit.tsx",
      "parent": "/dashboard/projects/$projectId/buildings/$buildingId"
    },
    "/dashboard/projects/$projectId/buildings/$buildingId/floors": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.floors.tsx",
      "parent": "/dashboard/projects/$projectId/buildings/$buildingId",
      "children": [
        "/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId"
      ]
    },
    "/dashboard/projects/$projectId/buildings/$buildingId/": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.index.tsx",
      "parent": "/dashboard/projects/$projectId/buildings/$buildingId"
    },
    "/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.floors.$floorId.tsx",
      "parent": "/dashboard/projects/$projectId/buildings/$buildingId/floors",
      "children": [
        "/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit"
      ]
    },
    "/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId/edit": {
      "filePath": "dashboard/projects/$projectId.buildings.$buildingId.floors.$floorId.edit.tsx",
      "parent": "/dashboard/projects/$projectId/buildings/$buildingId/floors/$floorId"
    }
  }
}
ROUTE_MANIFEST_END */
