/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthPendingAccessImport } from './routes/auth/pending-access'
import { Route as AuthOnboardingImport } from './routes/auth/onboarding'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AuthCreateAccountImport } from './routes/auth/create-account'
import { Route as AuthAcceptInviteImport } from './routes/auth/accept-invite'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminCompaniesImport } from './routes/admin/companies'
import { Route as AdminAccessRequestsImport } from './routes/admin/access-requests'
import { Route as DashboardProjectsIndexImport } from './routes/dashboard/projects/index'
import { Route as DashboardFieldIndexImport } from './routes/dashboard/field/index'
import { Route as DashboardCompanyIndexImport } from './routes/dashboard/company/index'
import { Route as DashboardAnalyticsIndexImport } from './routes/dashboard/analytics/index'
import { Route as DashboardProjectsProjectIdentifierImport } from './routes/dashboard/projects/$projectIdentifier'
import { Route as DashboardCompanyRolesImport } from './routes/dashboard/company/roles'
import { Route as DashboardCompanyProjectsImport } from './routes/dashboard/company/projects'
import { Route as DashboardCompanyMembersImport } from './routes/dashboard/company/members'
import { Route as DashboardCompanyInvitationsImport } from './routes/dashboard/company/invitations'
import { Route as DashboardProjectsProjectIdentifierIndexImport } from './routes/dashboard/projects/$projectIdentifier.index'
import { Route as DashboardAnalyticsProjectsIndexImport } from './routes/dashboard/analytics/projects.index'
import { Route as DashboardProjectsProjectIdentifierEditImport } from './routes/dashboard/projects/$projectIdentifier.edit'
import { Route as DashboardProjectsProjectIdentifierBuildingsImport } from './routes/dashboard/projects/$projectIdentifier.buildings'
import { Route as DashboardFieldProjectsProjectIdentifierImport } from './routes/dashboard/field/projects.$projectIdentifier'
import { Route as DashboardAnalyticsProjectsProjectIdentifierImport } from './routes/dashboard/analytics/projects.$projectIdentifier'
import { Route as DashboardProjectsProjectIdentifierBuildingsIndexImport } from './routes/dashboard/projects/$projectIdentifier.buildings.index'
import { Route as DashboardProjectsProjectIdentifierPoursNewImport } from './routes/dashboard/projects/$projectIdentifier.pours.new'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.index'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.edit'
import { Route as DashboardFieldProjectsProjectIdentifierPoursQuickAddImport } from './routes/dashboard/field/projects.$projectIdentifier.pours.quick-add'
import { Route as DashboardFieldProjectsProjectIdentifierPhotosUploadImport } from './routes/dashboard/field/projects.$projectIdentifier.photos.upload'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors.$floorIdentifier'
import { Route as DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditImport } from './routes/dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors.$floorIdentifier.edit'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthPendingAccessRoute = AuthPendingAccessImport.update({
  id: '/auth/pending-access',
  path: '/auth/pending-access',
  getParentRoute: () => rootRoute,
} as any)

const AuthOnboardingRoute = AuthOnboardingImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthCreateAccountRoute = AuthCreateAccountImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRoute,
} as any)

const AuthAcceptInviteRoute = AuthAcceptInviteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCompaniesRoute = AdminCompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAccessRequestsRoute = AdminAccessRequestsImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardProjectsIndexRoute = DashboardProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFieldIndexRoute = DashboardFieldIndexImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyIndexRoute = DashboardCompanyIndexImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProjectsProjectIdentifierRoute =
  DashboardProjectsProjectIdentifierImport.update({
    id: '/projects/$projectIdentifier',
    path: '/projects/$projectIdentifier',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardCompanyRolesRoute = DashboardCompanyRolesImport.update({
  id: '/company/roles',
  path: '/company/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyProjectsRoute = DashboardCompanyProjectsImport.update({
  id: '/company/projects',
  path: '/company/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyMembersRoute = DashboardCompanyMembersImport.update({
  id: '/company/members',
  path: '/company/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardCompanyInvitationsRoute =
  DashboardCompanyInvitationsImport.update({
    id: '/company/invitations',
    path: '/company/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdentifierIndexRoute =
  DashboardProjectsProjectIdentifierIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdentifierRoute,
  } as any)

const DashboardAnalyticsProjectsIndexRoute =
  DashboardAnalyticsProjectsIndexImport.update({
    id: '/analytics/projects/',
    path: '/analytics/projects/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdentifierEditRoute =
  DashboardProjectsProjectIdentifierEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectsProjectIdentifierRoute,
  } as any)

const DashboardProjectsProjectIdentifierBuildingsRoute =
  DashboardProjectsProjectIdentifierBuildingsImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => DashboardProjectsProjectIdentifierRoute,
  } as any)

const DashboardFieldProjectsProjectIdentifierRoute =
  DashboardFieldProjectsProjectIdentifierImport.update({
    id: '/field/projects/$projectIdentifier',
    path: '/field/projects/$projectIdentifier',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardAnalyticsProjectsProjectIdentifierRoute =
  DashboardAnalyticsProjectsProjectIdentifierImport.update({
    id: '/analytics/projects/$projectIdentifier',
    path: '/analytics/projects/$projectIdentifier',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

const DashboardProjectsProjectIdentifierBuildingsIndexRoute =
  DashboardProjectsProjectIdentifierBuildingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdentifierBuildingsRoute,
  } as any)

const DashboardProjectsProjectIdentifierPoursNewRoute =
  DashboardProjectsProjectIdentifierPoursNewImport.update({
    id: '/pours/new',
    path: '/pours/new',
    getParentRoute: () => DashboardProjectsProjectIdentifierRoute,
  } as any)

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport.update({
    id: '/$buildingIdentifier',
    path: '/$buildingIdentifier',
    getParentRoute: () => DashboardProjectsProjectIdentifierBuildingsRoute,
  } as any)

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute,
    } as any,
  )

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsImport.update(
    {
      id: '/floors',
      path: '/floors',
      getParentRoute: () =>
        DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute,
    } as any,
  )

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute,
    } as any,
  )

const DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute =
  DashboardFieldProjectsProjectIdentifierPoursQuickAddImport.update({
    id: '/pours/quick-add',
    path: '/pours/quick-add',
    getParentRoute: () => DashboardFieldProjectsProjectIdentifierRoute,
  } as any)

const DashboardFieldProjectsProjectIdentifierPhotosUploadRoute =
  DashboardFieldProjectsProjectIdentifierPhotosUploadImport.update({
    id: '/photos/upload',
    path: '/photos/upload',
    getParentRoute: () => DashboardFieldProjectsProjectIdentifierRoute,
  } as any)

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierImport.update(
    {
      id: '/$floorIdentifier',
      path: '/$floorIdentifier',
      getParentRoute: () =>
        DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRoute,
    } as any,
  )

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/access-requests': {
      id: '/admin/access-requests'
      path: '/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteImport
      parentRoute: typeof rootRoute
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/auth/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingImport
      parentRoute: typeof rootRoute
    }
    '/auth/pending-access': {
      id: '/auth/pending-access'
      path: '/auth/pending-access'
      fullPath: '/auth/pending-access'
      preLoaderRoute: typeof AuthPendingAccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/invitations': {
      id: '/dashboard/company/invitations'
      path: '/company/invitations'
      fullPath: '/dashboard/company/invitations'
      preLoaderRoute: typeof DashboardCompanyInvitationsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/members': {
      id: '/dashboard/company/members'
      path: '/company/members'
      fullPath: '/dashboard/company/members'
      preLoaderRoute: typeof DashboardCompanyMembersImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/projects': {
      id: '/dashboard/company/projects'
      path: '/company/projects'
      fullPath: '/dashboard/company/projects'
      preLoaderRoute: typeof DashboardCompanyProjectsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/roles': {
      id: '/dashboard/company/roles'
      path: '/company/roles'
      fullPath: '/dashboard/company/roles'
      preLoaderRoute: typeof DashboardCompanyRolesImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectIdentifier': {
      id: '/dashboard/projects/$projectIdentifier'
      path: '/projects/$projectIdentifier'
      fullPath: '/dashboard/projects/$projectIdentifier'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/company/': {
      id: '/dashboard/company/'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof DashboardCompanyIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/field/': {
      id: '/dashboard/field/'
      path: '/field'
      fullPath: '/dashboard/field'
      preLoaderRoute: typeof DashboardFieldIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/analytics/projects/$projectIdentifier': {
      id: '/dashboard/analytics/projects/$projectIdentifier'
      path: '/analytics/projects/$projectIdentifier'
      fullPath: '/dashboard/analytics/projects/$projectIdentifier'
      preLoaderRoute: typeof DashboardAnalyticsProjectsProjectIdentifierImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/field/projects/$projectIdentifier': {
      id: '/dashboard/field/projects/$projectIdentifier'
      path: '/field/projects/$projectIdentifier'
      fullPath: '/dashboard/field/projects/$projectIdentifier'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdentifierImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectIdentifier/buildings': {
      id: '/dashboard/projects/$projectIdentifier/buildings'
      path: '/buildings'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsImport
      parentRoute: typeof DashboardProjectsProjectIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/edit': {
      id: '/dashboard/projects/$projectIdentifier/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectIdentifier/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierEditImport
      parentRoute: typeof DashboardProjectsProjectIdentifierImport
    }
    '/dashboard/analytics/projects/': {
      id: '/dashboard/analytics/projects/'
      path: '/analytics/projects'
      fullPath: '/dashboard/analytics/projects'
      preLoaderRoute: typeof DashboardAnalyticsProjectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectIdentifier/': {
      id: '/dashboard/projects/$projectIdentifier/'
      path: '/'
      fullPath: '/dashboard/projects/$projectIdentifier/'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierIndexImport
      parentRoute: typeof DashboardProjectsProjectIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier'
      path: '/$buildingIdentifier'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsImport
    }
    '/dashboard/projects/$projectIdentifier/pours/new': {
      id: '/dashboard/projects/$projectIdentifier/pours/new'
      path: '/pours/new'
      fullPath: '/dashboard/projects/$projectIdentifier/pours/new'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierPoursNewImport
      parentRoute: typeof DashboardProjectsProjectIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/': {
      id: '/dashboard/projects/$projectIdentifier/buildings/'
      path: '/'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsIndexImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsImport
    }
    '/dashboard/field/projects/$projectIdentifier/photos/upload': {
      id: '/dashboard/field/projects/$projectIdentifier/photos/upload'
      path: '/photos/upload'
      fullPath: '/dashboard/field/projects/$projectIdentifier/photos/upload'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdentifierPhotosUploadImport
      parentRoute: typeof DashboardFieldProjectsProjectIdentifierImport
    }
    '/dashboard/field/projects/$projectIdentifier/pours/quick-add': {
      id: '/dashboard/field/projects/$projectIdentifier/pours/quick-add'
      path: '/pours/quick-add'
      fullPath: '/dashboard/field/projects/$projectIdentifier/pours/quick-add'
      preLoaderRoute: typeof DashboardFieldProjectsProjectIdentifierPoursQuickAddImport
      parentRoute: typeof DashboardFieldProjectsProjectIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors'
      path: '/floors'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/'
      path: '/'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier'
      path: '/$floorIdentifier'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsImport
    }
    '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit': {
      id: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditImport
      parentRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteChildren {
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute
}

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteChildren: DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteChildren =
  {
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute,
  }

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRoute._addFileChildren(
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteChildren,
  )

interface DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteChildren {
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren
}

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteChildren: DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteChildren =
  {
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren,
  }

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRoute._addFileChildren(
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteChildren,
  )

interface DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteChildren {
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute
}

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteChildren: DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteChildren =
  {
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute,
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren,
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute,
  }

const DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteWithChildren =
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute._addFileChildren(
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteChildren,
  )

interface DashboardProjectsProjectIdentifierBuildingsRouteChildren {
  DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute: typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteWithChildren
  DashboardProjectsProjectIdentifierBuildingsIndexRoute: typeof DashboardProjectsProjectIdentifierBuildingsIndexRoute
}

const DashboardProjectsProjectIdentifierBuildingsRouteChildren: DashboardProjectsProjectIdentifierBuildingsRouteChildren =
  {
    DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRoute:
      DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteWithChildren,
    DashboardProjectsProjectIdentifierBuildingsIndexRoute:
      DashboardProjectsProjectIdentifierBuildingsIndexRoute,
  }

const DashboardProjectsProjectIdentifierBuildingsRouteWithChildren =
  DashboardProjectsProjectIdentifierBuildingsRoute._addFileChildren(
    DashboardProjectsProjectIdentifierBuildingsRouteChildren,
  )

interface DashboardProjectsProjectIdentifierRouteChildren {
  DashboardProjectsProjectIdentifierBuildingsRoute: typeof DashboardProjectsProjectIdentifierBuildingsRouteWithChildren
  DashboardProjectsProjectIdentifierEditRoute: typeof DashboardProjectsProjectIdentifierEditRoute
  DashboardProjectsProjectIdentifierIndexRoute: typeof DashboardProjectsProjectIdentifierIndexRoute
  DashboardProjectsProjectIdentifierPoursNewRoute: typeof DashboardProjectsProjectIdentifierPoursNewRoute
}

const DashboardProjectsProjectIdentifierRouteChildren: DashboardProjectsProjectIdentifierRouteChildren =
  {
    DashboardProjectsProjectIdentifierBuildingsRoute:
      DashboardProjectsProjectIdentifierBuildingsRouteWithChildren,
    DashboardProjectsProjectIdentifierEditRoute:
      DashboardProjectsProjectIdentifierEditRoute,
    DashboardProjectsProjectIdentifierIndexRoute:
      DashboardProjectsProjectIdentifierIndexRoute,
    DashboardProjectsProjectIdentifierPoursNewRoute:
      DashboardProjectsProjectIdentifierPoursNewRoute,
  }

const DashboardProjectsProjectIdentifierRouteWithChildren =
  DashboardProjectsProjectIdentifierRoute._addFileChildren(
    DashboardProjectsProjectIdentifierRouteChildren,
  )

interface DashboardFieldProjectsProjectIdentifierRouteChildren {
  DashboardFieldProjectsProjectIdentifierPhotosUploadRoute: typeof DashboardFieldProjectsProjectIdentifierPhotosUploadRoute
  DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute: typeof DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute
}

const DashboardFieldProjectsProjectIdentifierRouteChildren: DashboardFieldProjectsProjectIdentifierRouteChildren =
  {
    DashboardFieldProjectsProjectIdentifierPhotosUploadRoute:
      DashboardFieldProjectsProjectIdentifierPhotosUploadRoute,
    DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute:
      DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute,
  }

const DashboardFieldProjectsProjectIdentifierRouteWithChildren =
  DashboardFieldProjectsProjectIdentifierRoute._addFileChildren(
    DashboardFieldProjectsProjectIdentifierRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCompanyInvitationsRoute: typeof DashboardCompanyInvitationsRoute
  DashboardCompanyMembersRoute: typeof DashboardCompanyMembersRoute
  DashboardCompanyProjectsRoute: typeof DashboardCompanyProjectsRoute
  DashboardCompanyRolesRoute: typeof DashboardCompanyRolesRoute
  DashboardProjectsProjectIdentifierRoute: typeof DashboardProjectsProjectIdentifierRouteWithChildren
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardCompanyIndexRoute: typeof DashboardCompanyIndexRoute
  DashboardFieldIndexRoute: typeof DashboardFieldIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardAnalyticsProjectsProjectIdentifierRoute: typeof DashboardAnalyticsProjectsProjectIdentifierRoute
  DashboardFieldProjectsProjectIdentifierRoute: typeof DashboardFieldProjectsProjectIdentifierRouteWithChildren
  DashboardAnalyticsProjectsIndexRoute: typeof DashboardAnalyticsProjectsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCompanyInvitationsRoute: DashboardCompanyInvitationsRoute,
  DashboardCompanyMembersRoute: DashboardCompanyMembersRoute,
  DashboardCompanyProjectsRoute: DashboardCompanyProjectsRoute,
  DashboardCompanyRolesRoute: DashboardCompanyRolesRoute,
  DashboardProjectsProjectIdentifierRoute:
    DashboardProjectsProjectIdentifierRouteWithChildren,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardCompanyIndexRoute: DashboardCompanyIndexRoute,
  DashboardFieldIndexRoute: DashboardFieldIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardAnalyticsProjectsProjectIdentifierRoute:
    DashboardAnalyticsProjectsProjectIdentifierRoute,
  DashboardFieldProjectsProjectIdentifierRoute:
    DashboardFieldProjectsProjectIdentifierRouteWithChildren,
  DashboardAnalyticsProjectsIndexRoute: DashboardAnalyticsProjectsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/projects/$projectIdentifier': typeof DashboardProjectsProjectIdentifierRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company': typeof DashboardCompanyIndexRoute
  '/dashboard/field': typeof DashboardFieldIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectIdentifier': typeof DashboardAnalyticsProjectsProjectIdentifierRoute
  '/dashboard/field/projects/$projectIdentifier': typeof DashboardFieldProjectsProjectIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings': typeof DashboardProjectsProjectIdentifierBuildingsRouteWithChildren
  '/dashboard/projects/$projectIdentifier/edit': typeof DashboardProjectsProjectIdentifierEditRoute
  '/dashboard/analytics/projects': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectIdentifier/': typeof DashboardProjectsProjectIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/pours/new': typeof DashboardProjectsProjectIdentifierPoursNewRoute
  '/dashboard/projects/$projectIdentifier/buildings/': typeof DashboardProjectsProjectIdentifierBuildingsIndexRoute
  '/dashboard/field/projects/$projectIdentifier/photos/upload': typeof DashboardFieldProjectsProjectIdentifierPhotosUploadRoute
  '/dashboard/field/projects/$projectIdentifier/pours/quick-add': typeof DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company': typeof DashboardCompanyIndexRoute
  '/dashboard/field': typeof DashboardFieldIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectIdentifier': typeof DashboardAnalyticsProjectsProjectIdentifierRoute
  '/dashboard/field/projects/$projectIdentifier': typeof DashboardFieldProjectsProjectIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/edit': typeof DashboardProjectsProjectIdentifierEditRoute
  '/dashboard/analytics/projects': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectIdentifier': typeof DashboardProjectsProjectIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/pours/new': typeof DashboardProjectsProjectIdentifierPoursNewRoute
  '/dashboard/projects/$projectIdentifier/buildings': typeof DashboardProjectsProjectIdentifierBuildingsIndexRoute
  '/dashboard/field/projects/$projectIdentifier/photos/upload': typeof DashboardFieldProjectsProjectIdentifierPhotosUploadRoute
  '/dashboard/field/projects/$projectIdentifier/pours/quick-add': typeof DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/company/invitations': typeof DashboardCompanyInvitationsRoute
  '/dashboard/company/members': typeof DashboardCompanyMembersRoute
  '/dashboard/company/projects': typeof DashboardCompanyProjectsRoute
  '/dashboard/company/roles': typeof DashboardCompanyRolesRoute
  '/dashboard/projects/$projectIdentifier': typeof DashboardProjectsProjectIdentifierRouteWithChildren
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/company/': typeof DashboardCompanyIndexRoute
  '/dashboard/field/': typeof DashboardFieldIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/analytics/projects/$projectIdentifier': typeof DashboardAnalyticsProjectsProjectIdentifierRoute
  '/dashboard/field/projects/$projectIdentifier': typeof DashboardFieldProjectsProjectIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings': typeof DashboardProjectsProjectIdentifierBuildingsRouteWithChildren
  '/dashboard/projects/$projectIdentifier/edit': typeof DashboardProjectsProjectIdentifierEditRoute
  '/dashboard/analytics/projects/': typeof DashboardAnalyticsProjectsIndexRoute
  '/dashboard/projects/$projectIdentifier/': typeof DashboardProjectsProjectIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/pours/new': typeof DashboardProjectsProjectIdentifierPoursNewRoute
  '/dashboard/projects/$projectIdentifier/buildings/': typeof DashboardProjectsProjectIdentifierBuildingsIndexRoute
  '/dashboard/field/projects/$projectIdentifier/photos/upload': typeof DashboardFieldProjectsProjectIdentifierPhotosUploadRoute
  '/dashboard/field/projects/$projectIdentifier/pours/quick-add': typeof DashboardFieldProjectsProjectIdentifierPoursQuickAddRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierEditRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierIndexRoute
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierRouteWithChildren
  '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit': typeof DashboardProjectsProjectIdentifierBuildingsBuildingIdentifierFloorsFloorIdentifierEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/projects/$projectIdentifier'
    | '/dashboard/analytics'
    | '/dashboard/company'
    | '/dashboard/field'
    | '/dashboard/projects'
    | '/dashboard/analytics/projects/$projectIdentifier'
    | '/dashboard/field/projects/$projectIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings'
    | '/dashboard/projects/$projectIdentifier/edit'
    | '/dashboard/analytics/projects'
    | '/dashboard/projects/$projectIdentifier/'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier'
    | '/dashboard/projects/$projectIdentifier/pours/new'
    | '/dashboard/projects/$projectIdentifier/buildings/'
    | '/dashboard/field/projects/$projectIdentifier/photos/upload'
    | '/dashboard/field/projects/$projectIdentifier/pours/quick-add'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/analytics'
    | '/dashboard/company'
    | '/dashboard/field'
    | '/dashboard/projects'
    | '/dashboard/analytics/projects/$projectIdentifier'
    | '/dashboard/field/projects/$projectIdentifier'
    | '/dashboard/projects/$projectIdentifier/edit'
    | '/dashboard/analytics/projects'
    | '/dashboard/projects/$projectIdentifier'
    | '/dashboard/projects/$projectIdentifier/pours/new'
    | '/dashboard/projects/$projectIdentifier/buildings'
    | '/dashboard/field/projects/$projectIdentifier/photos/upload'
    | '/dashboard/field/projects/$projectIdentifier/pours/quick-add'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/accept-invite'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/company/invitations'
    | '/dashboard/company/members'
    | '/dashboard/company/projects'
    | '/dashboard/company/roles'
    | '/dashboard/projects/$projectIdentifier'
    | '/dashboard/analytics/'
    | '/dashboard/company/'
    | '/dashboard/field/'
    | '/dashboard/projects/'
    | '/dashboard/analytics/projects/$projectIdentifier'
    | '/dashboard/field/projects/$projectIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings'
    | '/dashboard/projects/$projectIdentifier/edit'
    | '/dashboard/analytics/projects/'
    | '/dashboard/projects/$projectIdentifier/'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier'
    | '/dashboard/projects/$projectIdentifier/pours/new'
    | '/dashboard/projects/$projectIdentifier/buildings/'
    | '/dashboard/field/projects/$projectIdentifier/photos/upload'
    | '/dashboard/field/projects/$projectIdentifier/pours/quick-add'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier'
    | '/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthPendingAccessRoute: typeof AuthPendingAccessRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthPendingAccessRoute: AuthPendingAccessRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/dashboard",
        "/auth/accept-invite",
        "/auth/create-account",
        "/auth/forgot-password",
        "/auth/onboarding",
        "/auth/pending-access",
        "/auth/reset-password",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/access-requests",
        "/admin/companies",
        "/admin/users",
        "/admin/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/company/invitations",
        "/dashboard/company/members",
        "/dashboard/company/projects",
        "/dashboard/company/roles",
        "/dashboard/projects/$projectIdentifier",
        "/dashboard/analytics/",
        "/dashboard/company/",
        "/dashboard/field/",
        "/dashboard/projects/",
        "/dashboard/analytics/projects/$projectIdentifier",
        "/dashboard/field/projects/$projectIdentifier",
        "/dashboard/analytics/projects/"
      ]
    },
    "/admin/access-requests": {
      "filePath": "admin/access-requests.tsx",
      "parent": "/admin"
    },
    "/admin/companies": {
      "filePath": "admin/companies.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/auth/accept-invite": {
      "filePath": "auth/accept-invite.tsx"
    },
    "/auth/create-account": {
      "filePath": "auth/create-account.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/onboarding": {
      "filePath": "auth/onboarding.tsx"
    },
    "/auth/pending-access": {
      "filePath": "auth/pending-access.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/invitations": {
      "filePath": "dashboard/company/invitations.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/members": {
      "filePath": "dashboard/company/members.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/projects": {
      "filePath": "dashboard/company/projects.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/roles": {
      "filePath": "dashboard/company/roles.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectIdentifier": {
      "filePath": "dashboard/projects/$projectIdentifier.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/projects/$projectIdentifier/buildings",
        "/dashboard/projects/$projectIdentifier/edit",
        "/dashboard/projects/$projectIdentifier/",
        "/dashboard/projects/$projectIdentifier/pours/new"
      ]
    },
    "/dashboard/analytics/": {
      "filePath": "dashboard/analytics/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/company/": {
      "filePath": "dashboard/company/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/field/": {
      "filePath": "dashboard/field/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/": {
      "filePath": "dashboard/projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/analytics/projects/$projectIdentifier": {
      "filePath": "dashboard/analytics/projects.$projectIdentifier.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/field/projects/$projectIdentifier": {
      "filePath": "dashboard/field/projects.$projectIdentifier.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/field/projects/$projectIdentifier/photos/upload",
        "/dashboard/field/projects/$projectIdentifier/pours/quick-add"
      ]
    },
    "/dashboard/projects/$projectIdentifier/buildings": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.tsx",
      "parent": "/dashboard/projects/$projectIdentifier",
      "children": [
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier",
        "/dashboard/projects/$projectIdentifier/buildings/"
      ]
    },
    "/dashboard/projects/$projectIdentifier/edit": {
      "filePath": "dashboard/projects/$projectIdentifier.edit.tsx",
      "parent": "/dashboard/projects/$projectIdentifier"
    },
    "/dashboard/analytics/projects/": {
      "filePath": "dashboard/analytics/projects.index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectIdentifier/": {
      "filePath": "dashboard/projects/$projectIdentifier.index.tsx",
      "parent": "/dashboard/projects/$projectIdentifier"
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings",
      "children": [
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit",
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors",
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/"
      ]
    },
    "/dashboard/projects/$projectIdentifier/pours/new": {
      "filePath": "dashboard/projects/$projectIdentifier.pours.new.tsx",
      "parent": "/dashboard/projects/$projectIdentifier"
    },
    "/dashboard/projects/$projectIdentifier/buildings/": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.index.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings"
    },
    "/dashboard/field/projects/$projectIdentifier/photos/upload": {
      "filePath": "dashboard/field/projects.$projectIdentifier.photos.upload.tsx",
      "parent": "/dashboard/field/projects/$projectIdentifier"
    },
    "/dashboard/field/projects/$projectIdentifier/pours/quick-add": {
      "filePath": "dashboard/field/projects.$projectIdentifier.pours.quick-add.tsx",
      "parent": "/dashboard/field/projects/$projectIdentifier"
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/edit": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.edit.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier"
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier",
      "children": [
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier"
      ]
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.index.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier"
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors.$floorIdentifier.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors",
      "children": [
        "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit"
      ]
    },
    "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier/edit": {
      "filePath": "dashboard/projects/$projectIdentifier.buildings.$buildingIdentifier.floors.$floorIdentifier.edit.tsx",
      "parent": "/dashboard/projects/$projectIdentifier/buildings/$buildingIdentifier/floors/$floorIdentifier"
    }
  }
}
ROUTE_MANIFEST_END */
