/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthPendingAccessImport } from './routes/auth/pending-access'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AuthCreateAccountImport } from './routes/auth/create-account'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminCompaniesImport } from './routes/admin/companies'
import { Route as AdminAccessRequestsImport } from './routes/admin/access-requests'
import { Route as DashboardProjectsIndexImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsProjectIdImport } from './routes/dashboard/projects/$projectId'
import { Route as DashboardProjectsProjectIdEditImport } from './routes/dashboard/projects/$projectId.edit'
import { Route as DashboardProjectsProjectIdPoursNewImport } from './routes/dashboard/projects/$projectId.pours.new'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthPendingAccessRoute = AuthPendingAccessImport.update({
  id: '/auth/pending-access',
  path: '/auth/pending-access',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthCreateAccountRoute = AuthCreateAccountImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCompaniesRoute = AdminCompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAccessRequestsRoute = AdminAccessRequestsImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)

const DashboardProjectsIndexRoute = DashboardProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProjectsProjectIdRoute = DashboardProjectsProjectIdImport.update(
  {
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
)

const DashboardProjectsProjectIdEditRoute =
  DashboardProjectsProjectIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

const DashboardProjectsProjectIdPoursNewRoute =
  DashboardProjectsProjectIdPoursNewImport.update({
    id: '/pours/new',
    path: '/pours/new',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/access-requests': {
      id: '/admin/access-requests'
      path: '/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminRouteImport
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/auth/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/pending-access': {
      id: '/auth/pending-access'
      path: '/auth/pending-access'
      fullPath: '/auth/pending-access'
      preLoaderRoute: typeof AuthPendingAccessImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/projects/$projectId/edit': {
      id: '/dashboard/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/dashboard/projects/$projectId/edit'
      preLoaderRoute: typeof DashboardProjectsProjectIdEditImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
    '/dashboard/projects/$projectId/pours/new': {
      id: '/dashboard/projects/$projectId/pours/new'
      path: '/pours/new'
      fullPath: '/dashboard/projects/$projectId/pours/new'
      preLoaderRoute: typeof DashboardProjectsProjectIdPoursNewImport
      parentRoute: typeof DashboardProjectsProjectIdImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdEditRoute: typeof DashboardProjectsProjectIdEditRoute
  DashboardProjectsProjectIdPoursNewRoute: typeof DashboardProjectsProjectIdPoursNewRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdEditRoute: DashboardProjectsProjectIdEditRoute,
    DashboardProjectsProjectIdPoursNewRoute:
      DashboardProjectsProjectIdPoursNewRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/pending-access': typeof AuthPendingAccessRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/$projectId/edit': typeof DashboardProjectsProjectIdEditRoute
  '/dashboard/projects/$projectId/pours/new': typeof DashboardProjectsProjectIdPoursNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/pours/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/pours/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/admin/access-requests'
    | '/admin/companies'
    | '/admin/users'
    | '/auth/create-account'
    | '/auth/forgot-password'
    | '/auth/pending-access'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/'
    | '/dashboard/projects/$projectId/edit'
    | '/dashboard/projects/$projectId/pours/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthPendingAccessRoute: typeof AuthPendingAccessRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthPendingAccessRoute: AuthPendingAccessRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/dashboard",
        "/auth/create-account",
        "/auth/forgot-password",
        "/auth/pending-access",
        "/auth/reset-password",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/access-requests",
        "/admin/companies",
        "/admin/users",
        "/admin/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/projects/$projectId",
        "/dashboard/projects/"
      ]
    },
    "/admin/access-requests": {
      "filePath": "admin/access-requests.tsx",
      "parent": "/admin"
    },
    "/admin/companies": {
      "filePath": "admin/companies.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/auth/create-account": {
      "filePath": "auth/create-account.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/pending-access": {
      "filePath": "auth/pending-access.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectId": {
      "filePath": "dashboard/projects/$projectId.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/projects/$projectId/edit",
        "/dashboard/projects/$projectId/pours/new"
      ]
    },
    "/dashboard/projects/": {
      "filePath": "dashboard/projects/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/projects/$projectId/edit": {
      "filePath": "dashboard/projects/$projectId.edit.tsx",
      "parent": "/dashboard/projects/$projectId"
    },
    "/dashboard/projects/$projectId/pours/new": {
      "filePath": "dashboard/projects/$projectId.pours.new.tsx",
      "parent": "/dashboard/projects/$projectId"
    }
  }
}
ROUTE_MANIFEST_END */
